export const translations = {
  header: {
    home: { en: 'Home', zh: '主页' },
    solutions: { en: 'Solutions', zh: '解决方案' },
    industries: { en: 'Industrial Parks', zh: '产业园区' },
    labs: { en: 'Labs & Certification', zh: '实验室和认证机构' },
    trade: { en: 'Global Trade', zh: '全球贸易' },
    batteries: { en: 'Batteries & Modeling', zh: '电池与建模' },
    products: { en: 'Core Products', zh: '核心产品' },
    tsCloud: { en: 'TSu Cloud', zh: '天苏云' },
    tsPass: { en: 'TSu-Pass', zh: '绿境通' },
    aiTool: { en: 'AI Report Tool', zh: 'AI 报告工具' },
    blog: { en: 'TSu Panel', zh: '天苏面板' },
    tianSuTen: { en: 'TSu Ten Principles', zh: '天苏十条' },
    tianSuJilu: { en: 'TSu Collection', zh: '天苏辑录' },
    tianSuTalk: { en: 'TSu Discussions', zh: '天苏纵论' },
    contactUs: { en: 'Contact Us', zh: '联系我们' },
    sales: { en: 'Sales', zh: '淘宝' },
    aboutUs: { en: 'About Us', zh: '关于我们' },
    consultNow: { en: 'Consult Now', zh: '立即咨询' },
  },
  footer: {
    solutionsTitle: { en: 'Solutions & Products', zh: '解决方案和产品' },
    aboutTitle: { en: 'About TSu', zh: '关于天苏能源' },
    industrySolutions: { en: 'Digital Green Industrial Park Solutions', zh: '数字化绿色园区解决方案' },
    labSolutions: { en: 'AI Solutions for Labs & Certification', zh: '实验室与认证 AI 解决方案' },
    tradeSolutions: { en: 'Green Solutions for Cross-border Trade', zh: '跨境贸易绿色解决方案' },
    batteriesModeling: { en: 'Batteries & Modeling', zh: '电池与建模' },
    tsPass: { en: 'TSu-Pass™', zh: '绿境通 TSu-Pass™' },
    tsCloud: { en: 'TSu-Cloud', zh: '天苏云 TSu-Cloud' },
    aiTool: { en: 'AI Report Tool', zh: 'AI 报告工具' },
    aboutUs: { en: 'About Us', zh: '关于我们' },
    tianSuTen: { en: 'TSu Ten Principles', zh: '天苏十条' },
    tianSuTalk: { en: 'TSu Discussions', zh: '天苏纵论' },
    tianSuJilu: { en: 'TSu Collection', zh: '天苏辑录' },
    tsMall: { en: 'TSu Mall', zh: '天苏商城' },
    consultNow: { en: 'Consult Now', zh: '立即咨询' },
    email: { en: 'Email: haotian-ma@outlook.com', zh: '电子邮件： haotian-ma@outlook.com' },
    terms: { en: 'Terms', zh: '条款' },
    privacyPolicy: { en: 'Privacy Policy', zh: '隐私政策' },
    github: { en: 'GitHub', zh: 'GitHub' },
    footerNote: {
      en: 'All rights reserved by <a class="text-blue-600 underline dark:text-muted" href="https://github.com/TS-energy">TSu-Energy</a>.',
      zh: '版权所有 <a class="text-blue-600 underline dark:text-muted" href="https://github.com/TS-energy">TSu-Energy 天苏能源</a> · All rights reserved.'
    },
  }
};
